### PR TITLE
Switch to 232 and fix REPL

### PR DESCRIPTION
**Pull request by lancelote**

### CODE REVIEW

**Comment by PierreDeQuebec** [comment]
Hi lancelote,
Thank you for your work. I inserted the changes in my copy of the plugins and kept my changes on the list of USB identifiers in the Esp8266DeviceProvider class and recompiled the plugins. And it works!

I added the Adafruit ID (0x239A, 0x8038).

```
  override val usbIds: List<MicroPythonUsbId>
    get() = listOf(MicroPythonUsbId(0x1A86, 0x7523),
                   MicroPythonUsbId(0x10C4, 0xEA60),
                   MicroPythonUsbId(0x0403, 0x6001),
                   MicroPythonUsbId(0x239A, 0x8038))
```

**Comment by lancelote** [comment]
@PierreDeQuebec Thank you for taking a look at the changes 🙏 Would you like to open a pull request to add Metro M4 Airlift Lite support?

**Comment by PierreDeQuebec** [comment]
GitHub rejects my pull request because I am not a contributor. Not being a Git Jedi, I can't tell if I'm doing a pull request the wrong way.

**Comment by lancelote** [comment]
@PierreDeQuebec That's weird. Anyway, I created a PR on your behalf, I hope you don't mind - #254.

**Comment by Elizaveta239** [comment]
Hi @lancelote! Thank you very much for your fix! :)

**Comment by jesen2010** [comment]
Hi,pycharm-community-2023.2.4 REPL with the newest plug updated Oct 12 still can not work. Chip is esp32c3,but REPL in pycharm-community-2023.1.4 is working correctly.

**Comment by lancelote** [comment]
Hi @jesen2010, which OS do you use?

**Comment by jesen2010** [comment]
> Hi @jesen2010, which OS do you use?

Hi,lancelote,thanks for your quick reply,My OS:win10----Windows Feature Experience Pack 1000.19052.1000.0    My laptop's cpu is  AMD Ryzen 9 5900HX with Radeon Graphics ,Can it be caused by the cpu? I will try today with another laptop with intel cpu

**Comment by jesen2010** [comment]
> Hi @jesen2010, which OS do you use?

Hi lancelote,I did a test on another laptop with Intel CPU,REPL still can not work.

**Comment by lancelote** [comment]
It is OS-dependant. Should be fixed by  264, hopefully.

**Pull request merged**
