### PR TITLE
Type Hints for ESP32

### PR DESCRIPTION
**Pull request by MrNavaStar**
I have created type hints for the ESP32! This includes the esp module (it differs from the esp8266 esp module) and the esp32 module. I would like to also create hints for the espnow module, however I don't think it is yet in the main branch of micropython. Please let me know If I am wrong about this and I will make a pr with hints for it.

Please have a look over my hints and make sure there are no glaring issues, I have gone over a few times and I think they are pretty solid. The only remaining issues as far as I can tell are a few functions that have no comments. I was unable to find any description of what they do in the official micropython docs.

### CODE REVIEW

**Comment by Elizaveta239** [comment]
Thank you very much! I'll try to review it in the nearest future (or at least not later than January)

**Comment by MrNavaStar** [comment]
Sounds awesome! Ill keep adding any missing type hints as I run into them.

**Comment by PBrunot** [comment]
Wouldn't be just easier to install the package micropython-{esp32,...}-stubs ? Somebody else is already doing the hard-work to keep boards and micropython libraries in sync. Just add an additional dependency and we're good to go.
Tested with ESP32-WROOM32 (Lolin D32 board) / PyCharm 22.3 Community Edition.

**Comment by MrNavaStar** [comment]
> Wouldn't be just easier to install the package micropython-{esp32,...}-stubs ? Somebody else is already doing the hard-work to keep boards and micropython libraries in sync. Just add an additional dependency and we're good to go.

@PBrunot I had no idea this existed! Could you post a link? I agree that would be much better than manually keeping these up to date. 

Do you know of any similar packages for other boards or even the micropython core modules (as they too are out of date)

**Comment by MrNavaStar** [comment]
I think this one is different, but it seems to have cover all the boards this plug-in supports + the core modules. We could completely remove the type hints folder in this repo and just install from [here](https://github.com/Josverl/micropython-stubs)

**Comment by MrNavaStar** [comment]
@PBrunot I have been playing around with this library a bit and it seems to be lacking in a few major ways. The first is that there are no built in comments, and second many of the actual type hints are missing. As in functions do not say what data types the take in or return.

This is not very helpful beyond making the ide happy:
image

**Comment by PBrunot** [comment]
Yes you are right. Comments are a big drawback.


Le mar. 27 déc. 2022, 08:48, Ethan Stevenson ***@***.***> a
écrit :

**Comment by MrNavaStar** [comment]
Yeah Im not sure what they were thinking when they made this tool, but how are these hints helpful lol? They all just take args and kwargs return any:
image

I think the best way forward would be writing a custom tool that creates stubs based on the micropython docs

**Comment by PBrunot** [comment]
I spend some time yesterday looking into micropython code and it seems
clear to me that there is no way to extract detailed information from C
code (no descriptions, generic mp_obj_t , type and argcount check at
runtime). So parsing the docs maybe the best option indeed. I have not
understood yet the doc workflow with Sphynx that Micropython uses.

Le mer. 28 déc. 2022, 01:35, Ethan Stevenson ***@***.***> a
écrit :

**Comment by MrNavaStar** [comment]
That is correct, we cannot extract the comments from the c code. However, there is a repo called micropython-libs that contains the raw python for all of the micropython libraries. There are some comments in there. The rest of the comments would need to be extracted from the official docs

**Comment by MrNavaStar** [comment]
@Elizaveta239 Any update on this/how we need to move forward?

**Comment by Elizaveta239** [comment]
Hi! I'm very sorry for the late response! Thank you very much for the contribution!
Yes, it would be great to automate stub files generation, but currently I don't see how it can be done easily.

I'm closing the PR, It's merged into master. I'll fix some compatibility issues and will publish the new version of the plugin soon.
Thank you very much!

**Comment by Josverl** [comment]
Well, 
Automatically generated typestubs are available via https://github.com/Josverl/micropython-stubs#micropython-stubs and are published on PyPi for most major ports, boards and versions since V1.16 

These are generated by combining info for the boards, the frozen modules and the documentation.

Still not 100% perfect , but getting better with each PR to the MicroPython documentation

**Comment by berkut0** [comment]
Hi all
According to the changelog ESP32 should be supported.
but I'm not sure if I'm doing it right.
Should I choose ESP8266 for ESP32?

image

**Comment by megazhuk** [comment]
> Hi! I'm very sorry for the late response! Thank you very much for the contribution! Yes, it would be great to automate stub files generation, but currently I don't see how it can be done easily.
> 
> I'm closing the PR, It's merged into master. I'll fix some compatibility issues and will publish the new version of the plugin soon. Thank you very much!

Can't find `'esp32'` in `'Device type'` field in Micropython plugin options in Settings.
And `'esp32.pyi'` not used by PyCharm. 
I left `"ESP8266"` in the `"Device type"` field, and copied the **`esp32.pyi`** file from `\intellij-micropython\typehints\esp32` into the 
`\intellij-micropython\typehints\esp8266` folder.
Now it works, but the soul is not calm.
May be you can fix this ?

**Comment by Josverl** [comment]
Type-stubs are in the planning, and being worked on, for the Micropython project, based off the automated micropython -stubs that I created.

Hope that set your mind at ease.

**Pull request closed without merging**
