### PR TITLE
Fixed upload structure. Source and test folder handling now works

### PR DESCRIPTION
**Pull request by lukaskremla**
I have made modifications to the uploading logic. Source folders are now treated properly as before, test folders are skipped unless they are explicitly selected for the upload, only their contents get uploaded though, when they are selected - this might need to be fine-tuned according to your vision. 

I have tested this and it works for me, I haven't been able to find a bug in this.

### CODE REVIEW

**Comment by elmot** [comment]
Unfortunately, does not work normally with a project with several source roots, ex [layout-b](https://github.com/JetBrains/intellij-micropython/tree/elmot/nova-243/test-projects/layout-b)

**Comment by lukaskremla** [comment]
Okay, I can look into that, look at the included test layouts and see if I can get it working changing some code.

EDIT: I see what is wrong with files directly in the project being uploaded when there are marked source folders now. I can adjust the logic, I have only fixed the previous bug with uploads being weird overall.

**Comment by lukaskremla** [comment]
Please try the latest commit.

**Comment by elmot** [comment]
I am working now on adding some tests for this functionality. When it's done, I'll have a look

**Comment by lukaskremla** [comment]
Closing this PR as the changes have been consolidated into #347 due to being too intertwined with ones from other PRs.

**Pull request closed without merging**
